import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;

public class JPruebaBD extends javax.swing.JFrame {

    /**
     * Creates new form pruebaCon
     */
    public JPruebaBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnConectar)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnConectar)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        
        String bases = "";
        Connection con = null;
        Statement sql = null;
        ResultSet resultado = null;

        try {
            // Obtener conexión
            con = Conexion.getConnection();

            // Validar si la conexión fue exitosa
            if (con != null) {
                // Crear un statement
                sql = con.createStatement();

                // Consulta a la base de datos
                String consulta = "SELECT UsNom FROM TUsuario";

                // Ejecutar la consulta y obtener el resultado
                resultado = sql.executeQuery(consulta);

                // Procesar el resultado
                while (resultado.next()) {
                    bases += resultado.getString(1) + "\n";
                }

                // Mostrar las bases de datos
                JOptionPane.showMessageDialog(null, bases);
            } else {
                // Manejo en caso de que la conexión falle
                JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos.");
            }
            } catch (SQLException ex) {
                // Mostrar mensaje de error
                JOptionPane.showMessageDialog(null, ex.toString());
            } finally {
                // Cerrar recursos para evitar fugas de memoria
                try {
                    if (resultado != null) resultado.close();
                    if (sql != null) sql.close();
                    if (con != null) con.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.toString());
                }
            }
        /*String bases ="";
        
        try{
            Statement sql = Conexion.getConnection().createStatement();
            
            String consulta = "SELECT name from master.dbo.sysdatabases";
            
            ResultSet resultado = sql.executeQuery(consulta);
            
            while (resultado.next()){
                bases += resultado.getString(1) +"\n";
            }
            
            JOptionPane.showMessageDialog(null, bases);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }*/
    }//GEN-LAST:event_btnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPruebaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPruebaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPruebaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPruebaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPruebaBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    // End of variables declaration//GEN-END:variables
}
